### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Erulathra** [S1NU5-P1/Wbudy-STM32-Snake#1]
- [x] Add Termometer Handler
- [ ] Create Snake Logic
- [x] Add NES like Sprite renderer to ST7735 lib
- [x] Add  Button Handler
- [x] Clean ST7735
- [ ] Add RFID handler
- [ ] Add ADC handler
- [ ] Add PWM handler (screen brightness)
And more...
